// <auto-generated />
using System;
using FxRates.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FxRates.Infrastructure.Migrations
{
    [DbContext(typeof(RatesDbContext))]
    [Migration("20260911164918_InitialRates")]
    partial class InitialRates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FxRates.Infrastructure.RateEntity", b =>
                {
                    b.Property<string>("BaseCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("QuoteCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("Ask")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("Bid")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset?>("ProviderQuotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BaseCurrency", "QuoteCurrency");

                    b.ToTable("Rates", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rates_DifferentCurrencies", "\"BaseCurrency\" <> \"QuoteCurrency\"");

                            t.HasCheckConstraint("CK_Rates_Prices", "\"Bid\" > 0 AND \"Ask\" >= \"Bid\"");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
